// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace Flat4Me.Geo.YaMaps.Types
{

    public partial class GeocoderResponse
    {
        public class Thoroughfare2
        {

            [JsonProperty("ThoroughfareName")]
            public string ThoroughfareName { get; set; }

            [JsonProperty("Premise")]
            public Premise2 Premise { get; set; }
        }
    }

}
