//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Flat4Me.MailServiceCore {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class MailServiceSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static MailServiceSettings defaultInstance = ((MailServiceSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new MailServiceSettings())));
        
        public static MailServiceSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("msolyakov")]
        public string SendGridUser {
            get {
                return ((string)(this["SendGridUser"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Hd73nnXJ2E3V")]
        public string SendGridPassword {
            get {
                return ((string)(this["SendGridPassword"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("no-reply@flat4.me")]
        public string DefaultFromAddress {
            get {
                return ((string)(this["DefaultFromAddress"]));
            }
        }
    }
}
