//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Flat4Me.Data.Repository.Azure {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class StorageSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static StorageSettings defaultInstance = ((StorageSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new StorageSettings())));
        
        public static StorageSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CommonLog")]
        public string LogTableName {
            get {
                return ((string)(this["LogTableName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DefaultEndpointsProtocol=https;AccountName=flat4melog;AccountKey=pMBE38WS3/W+1772" +
            "TooaZxcxvAiPJYzuCgP+muTOddZBrgc8Jh8UA3GvuANiyqAb4tL2shrD/31pc9i6keO1vA==")]
        public string ConnectionString {
            get {
                return ((string)(this["ConnectionString"]));
            }
        }
    }
}
