//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Flat4Me.ImageServiceCore {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class ImageServiceSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static ImageServiceSettings defaultInstance = ((ImageServiceSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new ImageServiceSettings())));
        
        public static ImageServiceSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\flat4me\\img\\content\\1")]
        public string ImageStorageDiskPath {
            get {
                return ((string)(this["ImageStorageDiskPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost/img/content/1/{0}")]
        public string ImageUriPattern {
            get {
                return ((string)(this["ImageUriPattern"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ReplaceExistingImage {
            get {
                return ((bool)(this["ReplaceExistingImage"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DefaultEndpointsProtocol=https;AccountName=flat4medev;AccountKey=9no2AuNRceSS9nDH" +
            "kq3PtV81SpbozERxRlB2cUhuZ4aq6zrDxZOTnKfrC1W3dJ7ry+7P6Z1mHeys7tWIGF8IAg==")]
        public string AzureBlobConnectionString {
            get {
                return ((string)(this["AzureBlobConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("photos")]
        public string AzureBlobContainer {
            get {
                return ((string)(this["AzureBlobContainer"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://flat4medev.blob.core.windows.net/{0}/{1}")]
        public string AzureBlobPublicUriPattern {
            get {
                return ((string)(this["AzureBlobPublicUriPattern"]));
            }
        }
    }
}
