//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Flat4Me.Core.Rabbit {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    public sealed partial class RabbitClientConfig : global::System.Configuration.ApplicationSettingsBase {
        
        private static RabbitClientConfig defaultInstance = ((RabbitClientConfig)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new RabbitClientConfig())));
        
        public static RabbitClientConfig Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("f4me0dev-vpc.cloudapp.net")]
        public string RabbitHost {
            get {
                return ((string)(this["RabbitHost"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5672")]
        public string RabbitPort {
            get {
                return ((string)(this["RabbitPort"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("f4rabbit")]
        public string RabbitUser {
            get {
                return ((string)(this["RabbitUser"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1qaz@WSX3edc")]
        public string RabbitPassword {
            get {
                return ((string)(this["RabbitPassword"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/")]
        public string DefaultVirtualHost {
            get {
                return ((string)(this["DefaultVirtualHost"]));
            }
        }
    }
}
