// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace Flat4Me.Geo.YaMaps.Types
{

    public partial class GeocoderResponse
    {
        public class GeoObjectCollection2
        {

            [JsonProperty("metaDataProperty")]
            public MetaDataProperty2 MetaDataProperty { get; set; }

            [JsonProperty("featureMember")]
            public FeatureMember2[] FeatureMember { get; set; }
        }
    }

}
