// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace Flat4me.Maps.Yandex.Types
{

    public partial class ApiData
    {
        public partial class Feature
        {

            [JsonProperty("type")]
            public string Type { get; set; }

            [JsonProperty("geometry")]
            public Geometry2 Geometry { get; set; }

            [JsonProperty("properties")]
            public Properties2 Properties { get; set; }
        }
    }

}
