// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace Flat4me.Maps.Yandex.Types
{
    public partial class ApiData
    {
        public partial class Properties2
        {
            [JsonProperty("balloonContent")]
            public string BalloonContent { get; set; }

            [JsonProperty("hintContent")]
            public string HintContent { get; set; }
        }
    }
}