// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace Flat4me.Maps.Yandex.Types
{

    public partial class GeocoderResponse
    {
        public class Premise2
        {

            [JsonProperty("PremiseNumber")]
            public string PremiseNumber { get; set; }
        }
    }

}
