// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace Flat4me.Maps.Yandex.Types
{

    public partial class GeocoderResponse
    {
        public class GeoObject2
        {

            [JsonProperty("metaDataProperty")]
            public MetaDataProperty3 MetaDataProperty { get; set; }

            [JsonProperty("description")]
            public string Description { get; set; }

            [JsonProperty("name")]
            public string Name { get; set; }

            [JsonProperty("boundedBy")]
            public BoundedBy2 BoundedBy { get; set; }

            [JsonProperty("Point")]
            public Point2 Point { get; set; }
        }
    }

}
