// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace YaMaps
{

    public partial class GeocoderResponse
    {
        public class AddressDetails2
        {

            [JsonProperty("Country")]
            public Country2 Country { get; set; }
        }
    }

}
